### ISSUE TITLE
Androguard not working 

### ISSUE THREAD

**Issue by rathoreAbhi0208** [thealper2/androml#1]
Hi , 
a = APK(apk_file_path) is taking too long to run and notebook getting crashed tried with skip_analysis also
Also **from androguard.core.bytecodes.dvm import DalvikVMFormat** complains NOMODULE  **androguard.core.bytecodes.**

**Comment by thealper2** [comment]
Hi, you need to install version 3.3.5 of the library.

```python
pip install androguard==3.3.5
```

**Comment by rathoreAbhi0208** [comment]
Thanks man!!
